In [2]:
import numpy as np

In [5]:
mat1 = np.ones((3,4))
mat2 = np.zeros((5,3))
mat1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.savez('test.npz', Ones_Mat = mat1, Zeros_Mat = mat2)

In [8]:
with np.load('test.npz') as file:
    mat_1 = file['Ones_Mat']
    mat_2 = file['Zeros_Mat']
    print(mat_1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
m1 = np.array([[1,2,3],
               [0,0,0]])

m2 = np.array([[4,5,6],
               [1,1,1]])

vart_mat = np.vstack((m1,m2))
vart_mat

array([[1, 2, 3],
       [0, 0, 0],
       [4, 5, 6],
       [1, 1, 1]])

In [12]:
hori_mat = np.hstack((m1,m2))
hori_mat

array([[1, 2, 3, 4, 5, 6],
       [0, 0, 0, 1, 1, 1]])

In [14]:
s = 4
v = np.array([2,4,3,4,10])

v == s

array([False,  True, False,  True, False])

In [18]:
v = np.array([1,2,4,5,0])
print(np.all(v>1)) #true if all are true
print(np.any(v>1)) #true if any is true

False
True


In [ ]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,0,5,3])
np.isclose(v1,v2,atol=1)    #tolerance

array([ True,  True, False,  True, False])

In [22]:
v = np.array([2,4,3,4,10])
condition = v>=4
print(condition)

[False  True False  True  True]


In [23]:
v = np.array([2,4,3,4,10])
condition = v>=4
cond_access = v[condition]
print(cond_access)

[ 4  4 10]
