In [1]:
import numpy as np

In [16]:
s = np.array(5)
print(s.ndim)
print(s.shape)
v = np.array([1,2,3])
print("==============")
print(v.ndim)
print(v.shape)
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]
             ])
print("==============")
print(m.ndim)
print(m.shape)

0
()
1
(3,)
2
(3, 3)


In [19]:
vec1 = np.array([1,2,3,4,5,6])
mat1 = vec1.reshape(3,2)
print(vec1)
print(mat1)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [20]:
vec2 = np.array([1,2,3,4])
mat2 = vec2.reshape((vec2.shape[0],1))
print(vec2)
print(mat2)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]


In [22]:
vec2[:,None]

array([[1],
       [2],
       [3],
       [4]])

In [39]:
mat = np.array([[False,True,"Ayman"],
                [4,5,6],
                [7,8,9]
               ])
print(mat.dtype)
print(mat)

<U21
[['False' 'True' 'Ayman']
 ['4' '5' '6']
 ['7' '8' '9']]


Object, string, float, int, bool

In [33]:
class c:
    x=3
o1 = c()

In [43]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]
               ])
mat[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [44]:
transpose = mat.T
transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
mat3 = np.full((3,3),5) #empty  #identity   
mat3

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
angles = np.arange(0,361,90)
def rotate_img(angles):
    return img

In [46]:
np.random.random((3,3))

array([[0.59566248, 0.0106195 , 0.75486101],
       [0.74630387, 0.04370831, 0.61047634],
       [0.24556729, 0.66888437, 0.86916002]])

In [51]:
np.random.randint(0,11,(5,5))

array([[10,  7,  6,  1,  6],
       [ 2,  8,  7,  0,  1],
       [10,  0,  2,  4,  4],
       [ 1,  2,  0,  8,  6],
       [ 9,  9, 10,  8,  4]], dtype=int32)

In [50]:
a = ['ali',10,'amir',True]
np.random.choice(a,size=(3,5))

array([['amir', '10', 'True', '10', 'amir'],
       ['amir', '10', 'True', '10', 'True'],
       ['True', 'ali', 'amir', 'True', '10']], dtype='<U21')